### ISSUE TITLE
sposify features not working

### ISSUE THREAD

**Issue by NotADinosaur** [SpotCompiled/SpotC-Plus-Plus#49]
some things work but many of them don’t, for example "disable recommended songs section" or "disable storylines"
also it would be nice if you could have the lyrics above the "explore" section in the now playing view

**Comment by yodaluca23** [comment]
Yes, this is because Sposify hasn't been updated in forever so lots of the features to the different Spotify app elements don't work anymore. If you would like more of the features to be functional, you can downgrade to https://github.com/SpotCompiled/SpotC-Plus-Plus/releases/tag/v1.1.3 which is an older Spotify version that will work better with Sposify unfortunately I can't do anything about it on the newer versions unless it receives an update.
